/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;

/**
 *
 * @author IanSamuels
 */
public class TipoDeFiltro extends javax.swing.JFrame {
    private Controlador CONTROLADOR;
    
    public TipoDeFiltro(Controlador CONTROLADOR) {
        initComponents();
        this.CONTROLADOR = CONTROLADOR;
    }
    /**
     * Creates new form TipoDeFiltro
     */
    public TipoDeFiltro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonGeneral = new javax.swing.JButton();
        botonAluminio = new javax.swing.JButton();
        botonCoProcesable = new javax.swing.JButton();
        botonElectronica = new javax.swing.JButton();
        botonEscombros = new javax.swing.JButton();
        botonNoReciclable = new javax.swing.JButton();
        botonOrganica = new javax.swing.JButton();
        botonPlastico = new javax.swing.JButton();
        botonReciclable = new javax.swing.JButton();
        botonSanitario = new javax.swing.JButton();
        botonSemisintetico = new javax.swing.JButton();
        botonToxica = new javax.swing.JButton();
        botonVidrio = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione el tipo de filtro");

        botonGeneral.setText("General");
        botonGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGeneralActionPerformed(evt);
            }
        });

        botonAluminio.setText("Aluminio");
        botonAluminio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAluminioActionPerformed(evt);
            }
        });

        botonCoProcesable.setText("CoProcesable");
        botonCoProcesable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCoProcesableActionPerformed(evt);
            }
        });

        botonElectronica.setText("Electronica");
        botonElectronica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonElectronicaActionPerformed(evt);
            }
        });

        botonEscombros.setText("Escombros");
        botonEscombros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEscombrosActionPerformed(evt);
            }
        });

        botonNoReciclable.setText("NoReciclable");
        botonNoReciclable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNoReciclableActionPerformed(evt);
            }
        });

        botonOrganica.setText("Organica");
        botonOrganica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOrganicaActionPerformed(evt);
            }
        });

        botonPlastico.setText("Plastico");
        botonPlastico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPlasticoActionPerformed(evt);
            }
        });

        botonReciclable.setText("Reciclable");
        botonReciclable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReciclableActionPerformed(evt);
            }
        });

        botonSanitario.setText("Sanitaria");
        botonSanitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSanitarioActionPerformed(evt);
            }
        });

        botonSemisintetico.setText("Semisintetico");
        botonSemisintetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSemisinteticoActionPerformed(evt);
            }
        });

        botonToxica.setText("Toxica");
        botonToxica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonToxicaActionPerformed(evt);
            }
        });

        botonVidrio.setText("Vidrio");
        botonVidrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVidrioActionPerformed(evt);
            }
        });

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonPlastico)
                    .addComponent(botonNoReciclable)
                    .addComponent(botonCoProcesable)
                    .addComponent(botonAluminio)
                    .addComponent(botonElectronica)
                    .addComponent(botonEscombros))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonToxica)
                    .addComponent(botonVidrio)
                    .addComponent(botonSemisintetico)
                    .addComponent(botonOrganica)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botonReciclable)
                        .addComponent(botonSanitario)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botonAluminio, botonCoProcesable, botonElectronica, botonEscombros, botonNoReciclable, botonOrganica, botonPlastico, botonReciclable, botonSanitario, botonSemisintetico, botonToxica, botonVidrio});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonReciclable)
                    .addComponent(botonPlastico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAluminio)
                    .addComponent(botonSanitario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCoProcesable)
                    .addComponent(botonSemisintetico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonElectronica)
                    .addComponent(botonToxica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEscombros)
                    .addComponent(botonVidrio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNoReciclable)
                    .addComponent(botonOrganica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonGeneral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonVolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        MenuPrincipal ventanaMenuPrincipal = new MenuPrincipal(CONTROLADOR);
        ventanaMenuPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGeneralActionPerformed
        SeccionInformativa ventanaSeccionInformativa = new SeccionInformativa(CONTROLADOR,"General");
        ventanaSeccionInformativa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonGeneralActionPerformed

    private void botonPlasticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPlasticoActionPerformed
        SeccionInformativa ventanaSeccionInformativa = new SeccionInformativa(CONTROLADOR,"Plastico");
        ventanaSeccionInformativa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonPlasticoActionPerformed

    private void botonAluminioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAluminioActionPerformed
        SeccionInformativa ventanaSeccionInformativa = new SeccionInformativa(CONTROLADOR,"Aluminio");
        ventanaSeccionInformativa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonAluminioActionPerformed

    private void botonCoProcesableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCoProcesableActionPerformed
        SeccionInformativa ventanaSeccionInformativa = new SeccionInformativa(CONTROLADOR,"Coprocesable");
        ventanaSeccionInformativa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonCoProcesableActionPerformed

    private void botonElectronicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonElectronicaActionPerformed
        SeccionInformativa ventanaSeccionInformativa = new SeccionInformativa(CONTROLADOR,"Electronica");
        ventanaSeccionInformativa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonElectronicaActionPerformed

    private void botonEscombrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEscombrosActionPerformed
        SeccionInformativa ventanaSeccionInformativa = new SeccionInformativa(CONTROLADOR,"Escombros");
        ventanaSeccionInformativa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonEscombrosActionPerformed

    private void botonNoReciclableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNoReciclableActionPerformed
        SeccionInformativa ventanaSeccionInformativa = new SeccionInformativa(CONTROLADOR,"Noreciclable");
        ventanaSeccionInformativa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonNoReciclableActionPerformed

    private void botonReciclableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReciclableActionPerformed
        SeccionInformativa ventanaSeccionInformativa = new SeccionInformativa(CONTROLADOR,"Reciclable");
        ventanaSeccionInformativa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonReciclableActionPerformed

    private void botonSanitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSanitarioActionPerformed
        SeccionInformativa ventanaSeccionInformativa = new SeccionInformativa(CONTROLADOR,"Sanitaria");
        ventanaSeccionInformativa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonSanitarioActionPerformed

    private void botonSemisinteticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSemisinteticoActionPerformed
        SeccionInformativa ventanaSeccionInformativa = new SeccionInformativa(CONTROLADOR,"Semisintetico");
        ventanaSeccionInformativa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonSemisinteticoActionPerformed

    private void botonToxicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonToxicaActionPerformed
        SeccionInformativa ventanaSeccionInformativa = new SeccionInformativa(CONTROLADOR,"Toxica");
        ventanaSeccionInformativa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonToxicaActionPerformed

    private void botonVidrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVidrioActionPerformed
        SeccionInformativa ventanaSeccionInformativa = new SeccionInformativa(CONTROLADOR,"Vidrio");
        ventanaSeccionInformativa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonVidrioActionPerformed

    private void botonOrganicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOrganicaActionPerformed
        SeccionInformativa ventanaSeccionInformativa = new SeccionInformativa(CONTROLADOR,"Organica");
        ventanaSeccionInformativa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonOrganicaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAluminio;
    private javax.swing.JButton botonCoProcesable;
    private javax.swing.JButton botonElectronica;
    private javax.swing.JButton botonEscombros;
    private javax.swing.JButton botonGeneral;
    private javax.swing.JButton botonNoReciclable;
    private javax.swing.JButton botonOrganica;
    private javax.swing.JButton botonPlastico;
    private javax.swing.JButton botonReciclable;
    private javax.swing.JButton botonSanitario;
    private javax.swing.JButton botonSemisintetico;
    private javax.swing.JButton botonToxica;
    private javax.swing.JButton botonVidrio;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
